/**
 * AurumVault Audiobook Studio — Phase 2 QC rule evaluation (pure).
 *
 * Consumes already-measured signals (WavInfo from audiobook-wav.ts, metadata
 * evaluation, rights evaluation) and produces persistable check rows matching
 * the Phase 1 audiobook_qc_results shape.
 */
import type { WavInfo } from "@/lib/audiobook-wav";
import { evaluateAudiobookMetadata, type AudiobookMetadataInput } from "@/lib/audiobook-metadata";
import { evaluateRightsAttestation, type RightsAttestationInput } from "@/lib/audiobook-rights";

export type QcSeverity = "INFO" | "WARNING" | "BLOCKER";

export type QcCheck = {
  check_code: string;
  severity: QcSeverity;
  passed: boolean;
  detail: string;
  metrics: Record<string, unknown>;
};

export type QcInput = {
  metadata?: AudiobookMetadataInput | null;
  rights?: RightsAttestationInput | null;
  /** One entry per accepted audio asset. */
  audio?: Array<{ label: string; info: WavInfo; isMock: boolean }>;
  chapterCount?: number;
  chaptersWithAudio?: number;
};

export type QcEvaluation = {
  overallResult: "PASSED" | "PASSED_WITH_WARNINGS" | "FAILED";
  checks: QcCheck[];
};

export const MAX_CLIPPED_RATIO = 0.005;
export const MAX_SILENT_RATIO = 0.6;
export const MIN_DURATION_SECONDS = 1;

export function evaluateAudiobookQc(input: QcInput): QcEvaluation {
  const checks: QcCheck[] = [];

  const metaEval = evaluateAudiobookMetadata(input.metadata ?? {});
  checks.push({
    check_code: "METADATA_COMPLETE",
    severity: metaEval.isComplete ? "INFO" : "BLOCKER",
    passed: metaEval.isComplete,
    detail: metaEval.isComplete
      ? "Metadata has no blocking gaps."
      : `Metadata blockers: ${metaEval.blockers.map((b) => b.code).join(", ")}.`,
    metrics: { score: metaEval.score, blockers: metaEval.blockers.length, warnings: metaEval.warnings.length },
  });

  const rightsEval = evaluateRightsAttestation(input.rights);
  checks.push({
    check_code: "RIGHTS_ATTESTED",
    severity: rightsEval.blocked ? "BLOCKER" : "INFO",
    passed: !rightsEval.blocked,
    detail: rightsEval.blocked
      ? rightsEval.blockers.map((b) => b.message).join(" ")
      : "Rights attestation is recorded and current.",
    metrics: { blockers: rightsEval.blockers.length },
  });

  const audio = input.audio ?? [];
  if (audio.length === 0) {
    checks.push({
      check_code: "AUDIO_PRESENT",
      severity: "BLOCKER",
      passed: false,
      detail: "No accepted audio assets to check.",
      metrics: {},
    });
  } else {
    for (const item of audio) {
      checks.push({
        check_code: "AUDIO_CONTAINER_VALID",
        severity: item.info.ok ? "INFO" : "BLOCKER",
        passed: item.info.ok,
        detail: item.info.ok ? `${item.label}: valid WAV container.` : `${item.label}: ${item.info.reason ?? "invalid audio."}`,
        metrics: { label: item.label, sampleRate: item.info.sampleRate, truncated: item.info.truncated },
      });
      checks.push({
        check_code: "AUDIO_DURATION",
        severity: item.info.durationSeconds >= MIN_DURATION_SECONDS ? "INFO" : "BLOCKER",
        passed: item.info.durationSeconds >= MIN_DURATION_SECONDS,
        detail: `${item.label}: ${item.info.durationSeconds.toFixed(2)}s.`,
        metrics: { label: item.label, durationSeconds: item.info.durationSeconds },
      });
      checks.push({
        check_code: "AUDIO_CLIPPING",
        severity: item.info.clippedRatio <= MAX_CLIPPED_RATIO ? "INFO" : "WARNING",
        passed: item.info.clippedRatio <= MAX_CLIPPED_RATIO,
        detail: `${item.label}: clipped ratio ${item.info.clippedRatio.toFixed(4)}.`,
        metrics: { label: item.label, clippedRatio: item.info.clippedRatio },
      });
      checks.push({
        check_code: "AUDIO_DEAD_AIR",
        severity: item.info.silentRatio <= MAX_SILENT_RATIO ? "INFO" : "WARNING",
        passed: item.info.silentRatio <= MAX_SILENT_RATIO,
        detail: `${item.label}: silent ratio ${item.info.silentRatio.toFixed(4)}.`,
        metrics: { label: item.label, silentRatio: item.info.silentRatio },
      });
      if (item.isMock) {
        checks.push({
          check_code: "AUDIO_MOCK_NARRATION",
          severity: "BLOCKER",
          passed: false,
          detail: `${item.label}: generated by the mock narration provider — not distributable audio.`,
          metrics: { label: item.label, mock: true },
        });
      }
    }
  }

  if (typeof input.chapterCount === "number") {
    const covered = input.chaptersWithAudio ?? 0;
    const complete = input.chapterCount > 0 && covered >= input.chapterCount;
    checks.push({
      check_code: "AUDIO_CHAPTER_COVERAGE",
      severity: complete ? "INFO" : "BLOCKER",
      passed: complete,
      detail: `${covered}/${input.chapterCount} chapters have accepted audio.`,
      metrics: { chapterCount: input.chapterCount, chaptersWithAudio: covered },
    });
  }

  const failed = checks.some((c) => !c.passed && c.severity === "BLOCKER");
  const warned = checks.some((c) => !c.passed && c.severity === "WARNING");
  return {
    overallResult: failed ? "FAILED" : warned ? "PASSED_WITH_WARNINGS" : "PASSED",
    checks,
  };
}