/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DownloadTokenRouteImport } from './routes/download.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedDashboardNewRouteImport } from './routes/_authenticated/dashboard.new'
import { Route as AuthenticatedDashboardHelpRouteImport } from './routes/_authenticated/dashboard.help'
import { Route as AuthenticatedDashboardEarnRouteImport } from './routes/_authenticated/dashboard.earn'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksAuditCoversRouteImport } from './routes/api/public/hooks/audit-covers'
import { Route as ApiPublicHealthCategoriesRouteImport } from './routes/api/public/health/categories'
import { Route as AuthenticatedAdminHealthCoversRouteImport } from './routes/_authenticated/admin.health.covers'
import { Route as AuthenticatedAdminHealthCoversAlertsRouteImport } from './routes/_authenticated/admin.health.covers.alerts'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTokenRoute = DownloadTokenRouteImport.update({
  id: '/download/$token',
  path: '/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardNewRoute =
  AuthenticatedDashboardNewRouteImport.update({
    id: '/dashboard/new',
    path: '/dashboard/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHelpRoute =
  AuthenticatedDashboardHelpRouteImport.update({
    id: '/dashboard/help',
    path: '/dashboard/help',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEarnRoute =
  AuthenticatedDashboardEarnRouteImport.update({
    id: '/dashboard/earn',
    path: '/dashboard/earn',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAuditCoversRoute =
  ApiPublicHooksAuditCoversRouteImport.update({
    id: '/api/public/hooks/audit-covers',
    path: '/api/public/hooks/audit-covers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthCategoriesRoute =
  ApiPublicHealthCategoriesRouteImport.update({
    id: '/api/public/health/categories',
    path: '/api/public/health/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminHealthCoversRoute =
  AuthenticatedAdminHealthCoversRouteImport.update({
    id: '/health/covers',
    path: '/health/covers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthCoversAlertsRoute =
  AuthenticatedAdminHealthCoversAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdminHealthCoversRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vault': typeof VaultRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/download/$token': typeof DownloadTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/dashboard/earn': typeof AuthenticatedDashboardEarnRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/health/covers': typeof AuthenticatedAdminHealthCoversRouteWithChildren
  '/api/public/health/categories': typeof ApiPublicHealthCategoriesRoute
  '/api/public/hooks/audit-covers': typeof ApiPublicHooksAuditCoversRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/health/covers/alerts': typeof AuthenticatedAdminHealthCoversAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vault': typeof VaultRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/download/$token': typeof DownloadTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/$id': typeof ProductsIdRoute
  '/products': typeof ProductsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/dashboard/earn': typeof AuthenticatedDashboardEarnRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/health/covers': typeof AuthenticatedAdminHealthCoversRouteWithChildren
  '/api/public/health/categories': typeof ApiPublicHealthCategoriesRoute
  '/api/public/hooks/audit-covers': typeof ApiPublicHooksAuditCoversRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/health/covers/alerts': typeof AuthenticatedAdminHealthCoversAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vault': typeof VaultRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/download/$token': typeof DownloadTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/dashboard/earn': typeof AuthenticatedDashboardEarnRoute
  '/_authenticated/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/_authenticated/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/health/covers': typeof AuthenticatedAdminHealthCoversRouteWithChildren
  '/api/public/health/categories': typeof ApiPublicHealthCategoriesRoute
  '/api/public/hooks/audit-covers': typeof ApiPublicHooksAuditCoversRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/health/covers/alerts': typeof AuthenticatedAdminHealthCoversAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/products'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/vault'
    | '/wishlist'
    | '/admin'
    | '/checkout/return'
    | '/download/$token'
    | '/email/unsubscribe'
    | '/products/$id'
    | '/products/'
    | '/admin/products'
    | '/dashboard/earn'
    | '/dashboard/help'
    | '/dashboard/new'
    | '/lovable/email/suppression'
    | '/dashboard/'
    | '/admin/health/covers'
    | '/api/public/health/categories'
    | '/api/public/hooks/audit-covers'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/health/covers/alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/vault'
    | '/wishlist'
    | '/admin'
    | '/checkout/return'
    | '/download/$token'
    | '/email/unsubscribe'
    | '/products/$id'
    | '/products'
    | '/admin/products'
    | '/dashboard/earn'
    | '/dashboard/help'
    | '/dashboard/new'
    | '/lovable/email/suppression'
    | '/dashboard'
    | '/admin/health/covers'
    | '/api/public/health/categories'
    | '/api/public/hooks/audit-covers'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/health/covers/alerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/auth'
    | '/products'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/vault'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/checkout/return'
    | '/download/$token'
    | '/email/unsubscribe'
    | '/products/$id'
    | '/products/'
    | '/_authenticated/admin/products'
    | '/_authenticated/dashboard/earn'
    | '/_authenticated/dashboard/help'
    | '/_authenticated/dashboard/new'
    | '/lovable/email/suppression'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/health/covers'
    | '/api/public/health/categories'
    | '/api/public/hooks/audit-covers'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/health/covers/alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VaultRoute: typeof VaultRoute
  WishlistRoute: typeof WishlistRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DownloadTokenRoute: typeof DownloadTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHealthCategoriesRoute: typeof ApiPublicHealthCategoriesRoute
  ApiPublicHooksAuditCoversRoute: typeof ApiPublicHooksAuditCoversRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$token': {
      id: '/download/$token'
      path: '/download/$token'
      fullPath: '/download/$token'
      preLoaderRoute: typeof DownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/new': {
      id: '/_authenticated/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthenticatedDashboardNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/help': {
      id: '/_authenticated/dashboard/help'
      path: '/dashboard/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof AuthenticatedDashboardHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/earn': {
      id: '/_authenticated/dashboard/earn'
      path: '/dashboard/earn'
      fullPath: '/dashboard/earn'
      preLoaderRoute: typeof AuthenticatedDashboardEarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/audit-covers': {
      id: '/api/public/hooks/audit-covers'
      path: '/api/public/hooks/audit-covers'
      fullPath: '/api/public/hooks/audit-covers'
      preLoaderRoute: typeof ApiPublicHooksAuditCoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/categories': {
      id: '/api/public/health/categories'
      path: '/api/public/health/categories'
      fullPath: '/api/public/health/categories'
      preLoaderRoute: typeof ApiPublicHealthCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/health/covers': {
      id: '/_authenticated/admin/health/covers'
      path: '/health/covers'
      fullPath: '/admin/health/covers'
      preLoaderRoute: typeof AuthenticatedAdminHealthCoversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health/covers/alerts': {
      id: '/_authenticated/admin/health/covers/alerts'
      path: '/alerts'
      fullPath: '/admin/health/covers/alerts'
      preLoaderRoute: typeof AuthenticatedAdminHealthCoversAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminHealthCoversRoute
    }
  }
}

interface AuthenticatedAdminHealthCoversRouteChildren {
  AuthenticatedAdminHealthCoversAlertsRoute: typeof AuthenticatedAdminHealthCoversAlertsRoute
}

const AuthenticatedAdminHealthCoversRouteChildren: AuthenticatedAdminHealthCoversRouteChildren =
  {
    AuthenticatedAdminHealthCoversAlertsRoute:
      AuthenticatedAdminHealthCoversAlertsRoute,
  }

const AuthenticatedAdminHealthCoversRouteWithChildren =
  AuthenticatedAdminHealthCoversRoute._addFileChildren(
    AuthenticatedAdminHealthCoversRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminHealthCoversRoute: typeof AuthenticatedAdminHealthCoversRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminHealthCoversRoute:
    AuthenticatedAdminHealthCoversRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardEarnRoute: typeof AuthenticatedDashboardEarnRoute
  AuthenticatedDashboardHelpRoute: typeof AuthenticatedDashboardHelpRoute
  AuthenticatedDashboardNewRoute: typeof AuthenticatedDashboardNewRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardEarnRoute: AuthenticatedDashboardEarnRoute,
  AuthenticatedDashboardHelpRoute: AuthenticatedDashboardHelpRoute,
  AuthenticatedDashboardNewRoute: AuthenticatedDashboardNewRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VaultRoute: VaultRoute,
  WishlistRoute: WishlistRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DownloadTokenRoute: DownloadTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHealthCategoriesRoute: ApiPublicHealthCategoriesRoute,
  ApiPublicHooksAuditCoversRoute: ApiPublicHooksAuditCoversRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
