-- Food OS cross-tenant integrity phase 2. Applied to staging in five ordered migrations.
create unique index if not exists food_events_tenant_id_uidx on public.food_traceability_events(organization_id,id);
create unique index if not exists food_exceptions_tenant_id_uidx on public.food_traceability_exceptions(organization_id,id);
create unique index if not exists food_recalls_tenant_id_uidx on public.food_recall_cases(organization_id,id);
create unique index if not exists food_capa_tenant_id_uidx on public.food_corrective_actions(organization_id,id);
create unique index if not exists food_evidence_tenant_id_uidx on public.food_evidence(organization_id,id);
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_traceability_events'::regclass and conname='food_events_lot_tenant_fk') then alter table public.food_traceability_events add constraint food_events_lot_tenant_fk foreign key(organization_id,lot_id) references public.food_traceability_lots(organization_id,id); end if; if not exists (select 1 from pg_constraint where conrelid='public.food_traceability_events'::regclass and conname='food_events_facility_tenant_fk') then alter table public.food_traceability_events add constraint food_events_facility_tenant_fk foreign key(organization_id,facility_id) references public.food_facilities(organization_id,id); end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_event_kdes'::regclass and conname='food_kdes_event_tenant_fk') then alter table public.food_event_kdes add constraint food_kdes_event_tenant_fk foreign key(organization_id,event_id) references public.food_traceability_events(organization_id,id); end if;  end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_shipments'::regclass and conname='food_shipments_origin_tenant_fk') then alter table public.food_shipments add constraint food_shipments_origin_tenant_fk foreign key(organization_id,origin_facility_id) references public.food_facilities(organization_id,id); end if;  end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_traceability_exceptions'::regclass and conname='food_exceptions_event_tenant_fk') then alter table public.food_traceability_exceptions add constraint food_exceptions_event_tenant_fk foreign key(organization_id,event_id) references public.food_traceability_events(organization_id,id); end if; if not exists (select 1 from pg_constraint where conrelid='public.food_traceability_exceptions'::regclass and conname='food_exceptions_lot_tenant_fk') then alter table public.food_traceability_exceptions add constraint food_exceptions_lot_tenant_fk foreign key(organization_id,lot_id) references public.food_traceability_lots(organization_id,id); end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_corrective_actions'::regclass and conname='food_capa_exception_tenant_fk') then alter table public.food_corrective_actions add constraint food_capa_exception_tenant_fk foreign key(organization_id,exception_id) references public.food_traceability_exceptions(organization_id,id); end if; if not exists (select 1 from pg_constraint where conrelid='public.food_corrective_actions'::regclass and conname='food_capa_recall_tenant_fk') then alter table public.food_corrective_actions add constraint food_capa_recall_tenant_fk foreign key(organization_id,recall_id) references public.food_recall_cases(organization_id,id); end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_evidence'::regclass and conname='food_evidence_capa_tenant_fk') then alter table public.food_evidence add constraint food_evidence_capa_tenant_fk foreign key(organization_id,corrective_action_id) references public.food_corrective_actions(organization_id,id); end if;  end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_mock_record_requests'::regclass and conname='food_challenge_lot_tenant_fk') then alter table public.food_mock_record_requests add constraint food_challenge_lot_tenant_fk foreign key(organization_id,lot_id) references public.food_traceability_lots(organization_id,id); end if;  end $$;
do $$ begin if not exists (select 1 from pg_constraint where conrelid='public.food_recall_notifications'::regclass and conname='food_notifications_recall_tenant_fk') then alter table public.food_recall_notifications add constraint food_notifications_recall_tenant_fk foreign key(organization_id,recall_case_id) references public.food_recall_cases(organization_id,id); end if;  end $$;
alter table public.food_dispositions add constraint food_dispositions_lot_tenant_fk foreign key(organization_id,lot_id) references public.food_traceability_lots(organization_id,id), add constraint food_dispositions_recall_tenant_fk foreign key(organization_id,recall_case_id) references public.food_recall_cases(organization_id,id), add constraint food_dispositions_evidence_tenant_fk foreign key(organization_id,evidence_id) references public.food_evidence(organization_id,id);
create or replace function private.food_scope_same_tenant() returns trigger language plpgsql set search_path='' as $$
begin
 if not exists (select 1 from public.food_recall_cases r join public.food_traceability_lots l on l.organization_id=r.organization_id where r.id=new.recall_id and l.id=new.lot_id) then
  raise exception 'Recall scope lot must belong to recall organization';
 end if;
 return new;
end $$;
drop trigger if exists food_scope_tenant_guard on public.food_recall_scope_items;
create trigger food_scope_tenant_guard before insert or update on public.food_recall_scope_items for each row execute function private.food_scope_same_tenant();